### ISSUE TITLE
State should have active attribute

### ISSUE THREAD

**Issue by manglemix** [mechPenSketch/FiniteStateMachine#1]
This is not absolutely necessary, but makes it possible to check if a node is active. set_active should then be used as the setter

**Comment by mechPenSketch** [comment]
I didn't not give ```active``` a setter or getter as I reserve using ```setget``` for when the attribute is involved with the editor. I also find ```is_active()``` unnecessary as ```active``` itself could be called.

**Comment by mechPenSketch** [comment]
That said, I have just included ```is_active()``` in an update. Not that I agree to its inclusion since attributes here can't be set private so I felt setter and getter won't help secure the variable from potentially changing unintentionally, but others might be too used to having getters or expects this function when it's present on other nodes. I might also need to read up on setters and getters myself to see how needed it s, especially for this case.
